development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: demo_db
  suffix: development
  username: 
  password:
  
production:
  protocol: 'http'                                               
  host: < host >                  # VM IP
  port: < port >                  # VM Port
  prefix: < database name >       # Database Name a/c to prefix and suffix 
  suffix: production              # Database Name a/c to  prefix and suffix
  username: < user_name >         # User Name
  password: '< password >'        # Password